using System.Collections.Generic;
using System.Linq;

namespace D4BuildFilter.Core;

/// <summary>One S14 unique charm (the Talisman_Charm_Unique_* item form): display name + filter id.</summary>
public sealed record UniqueCharm(string Name, uint Id);

/// <summary>Every S14 unique charm (the Talisman_Charm_Unique_* forms that drop on the ground),
/// for the app's "Unique Charms" show-list (all pre-checked). GENERATED from the d4data dump
/// (maxroll data.min.json v3.1.x), 2026-07-04 — regenerate when a patch adds unique charms.</summary>
public static class UniqueCharmDatabase
{
    public static readonly IReadOnlyList<UniqueCharm> All = new[]
    {
        new UniqueCharm("Accord of the Wilds", 0x276d9eu),
        new UniqueCharm("Anathema of the Primes", 0x2790c7u),
        new UniqueCharm("Arcadia", 0x27824du),
        new UniqueCharm("Argent Veil", 0x27820eu),
        new UniqueCharm("Arreat's Bearing", 0x27905cu),
        new UniqueCharm("Assassin's Stride", 0x2783fau),
        new UniqueCharm("Azurewrath", 0x276db3u),
        new UniqueCharm("Balazan's Maxtlatl", 0x278c87u),
        new UniqueCharm("Band of First Breath", 0x278c9eu),
        new UniqueCharm("Banished Lord's Talisman", 0x276db6u),
        new UniqueCharm("Beastfall Boots", 0x278404u),
        new UniqueCharm("Blood Moon Breeches", 0x27965cu),
        new UniqueCharm("Blood-Mad Idol", 0x276db8u),
        new UniqueCharm("Bloodless Scream", 0x279656u),
        new UniqueCharm("Cathedral's Song", 0x278247u),
        new UniqueCharm("Chainscourged Mail", 0x27905eu),
        new UniqueCharm("Condemnation", 0x2783f6u),
        new UniqueCharm("Cowl of the Nameless", 0x2783f8u),
        new UniqueCharm("Crown of Lucion", 0x276de8u),
        new UniqueCharm("Dark Stalker's Medallion", 0x279066u),
        new UniqueCharm("Dirge of Airidah", 0x276d3fu),
        new UniqueCharm("Dirge of Odium", 0x2790cdu),
        new UniqueCharm("Drognan's Anguish", 0x279ec5u),
        new UniqueCharm("Echo of Kwatli", 0x278c98u),
        new UniqueCharm("Emberfury", 0x279ec1u),
        new UniqueCharm("Emblem of Staalbreak", 0x279064u),
        new UniqueCharm("Endurant Faith", 0x276de6u),
        new UniqueCharm("Esu's Heirloom", 0x279ec9u),
        new UniqueCharm("Etna's Lost Dagger", 0x2783fcu),
        new UniqueCharm("Fist of the Iron Rose", 0x2783f2u),
        new UniqueCharm("Fists of Fate", 0x276dc7u),
        new UniqueCharm("Fleshwrit Carapace", 0x2790d9u),
        new UniqueCharm("Flickerstep", 0x276dbdu),
        new UniqueCharm("Fractured Runestone", 0x276d9bu),
        new UniqueCharm("Frostburn", 0x276dc9u),
        new UniqueCharm("Fury of the Wilds", 0x276da2u),
        new UniqueCharm("Gladiator's Triumph", 0x2783eeu),
        new UniqueCharm("Godslayer Crown", 0x276dcfu),
        new UniqueCharm("Gravewalker's Hand", 0x279e8cu),
        new UniqueCharm("Greenwalker's Signet", 0x276d97u),
        new UniqueCharm("Griswold's Opus", 0x2781efu),
        new UniqueCharm("Harmony of Ebewaka", 0x278c79u),
        new UniqueCharm("Herald of Zakarum", 0x2781d8u),
        new UniqueCharm("Hooves of the Mountain God", 0x279060u),
        new UniqueCharm("Jacinth Shell", 0x278c6du),
        new UniqueCharm("Judicant's Glaivehelm", 0x278225u),
        new UniqueCharm("Locran's Talisman", 0x276de2u),
        new UniqueCharm("Loyalty's Mantle", 0x278c80u),
        new UniqueCharm("Mantle of the Grey", 0x278117u),
        new UniqueCharm("Mark of the Old Wolf", 0x276da0u),
        new UniqueCharm("Might of the Ursine", 0x276da4u),
        new UniqueCharm("Misericorde", 0x278402u),
        new UniqueCharm("Moloch's Beating Flame", 0x2790d1u),
        new UniqueCharm("Molten Band", 0x279ec3u),
        new UniqueCharm("Morlu Fleshward", 0x2790d7u),
        new UniqueCharm("Mother's Embrace", 0x276dd9u),
        new UniqueCharm("Night Terror", 0x2790d3u),
        new UniqueCharm("Nomad's Longing Heart", 0x279068u),
        new UniqueCharm("Omen of Pain", 0x279660u),
        new UniqueCharm("Orsivane", 0x279ebfu),
        new UniqueCharm("Pact of Bone", 0x27965eu),
        new UniqueCharm("Paingorger's Gauntlets", 0x276dcbu),
        new UniqueCharm("Peacemonger's Signet", 0x278ca0u),
        new UniqueCharm("Penitent Greaves", 0x276dbau),
        new UniqueCharm("Protean Heart", 0x278c9au),
        new UniqueCharm("Protection of the Prime", 0x278c85u),
        new UniqueCharm("Rage of Harrogath", 0x279056u),
        new UniqueCharm("Rakanoth's Wake", 0x276de4u),
        new UniqueCharm("Ramaladni's Magnum Opus", 0x279058u),
        new UniqueCharm("Razorplate", 0x276dc3u),
        new UniqueCharm("Red Blessing", 0x279658u),
        new UniqueCharm("Ring of Red Furor", 0x279062u),
        new UniqueCharm("Ring of the Midday Hunt", 0x278ca2u),
        new UniqueCharm("Ring of the Midnight Sun", 0x278c95u),
        new UniqueCharm("Ring of Writhing Moon", 0x278c93u),
        new UniqueCharm("Rod of Kepeleke", 0x278c8fu),
        new UniqueCharm("Rustbitten Dirk", 0x276db1u),
        new UniqueCharm("Saboteur's Signet", 0x278400u),
        new UniqueCharm("Sabre of Tsasgal", 0x27905au),
        new UniqueCharm("Sanctis of Kethamar", 0x278237u),
        new UniqueCharm("Scepter of the Three", 0x2790cbu),
        new UniqueCharm("Scoundrel's Kiss", 0x2783f0u),
        new UniqueCharm("Scoundrel's Leathers", 0x2783feu),
        new UniqueCharm("Sea Lord's Fine Gloves", 0x2783f4u),
        new UniqueCharm("Seal of the Second Trumpet", 0x27821du),
        new UniqueCharm("Seed of Horazon", 0x2790cfu),
        new UniqueCharm("Sepazontec", 0x278c8cu),
        new UniqueCharm("Soulbrand", 0x276dc5u),
        new UniqueCharm("Sunbird's Gorget", 0x278c5du),
        new UniqueCharm("Sundered Night", 0x27823fu),
        new UniqueCharm("Sunstained War-Crozier", 0x278c8au),
        new UniqueCharm("Tal Rasha's Iridescent Loop", 0x279ec7u),
        new UniqueCharm("Tassets of the Dawning Sky", 0x276dd5u),
        new UniqueCharm("Temerity", 0x276dd1u),
        new UniqueCharm("The Butcher's Cleaver", 0x276dadu),
        new UniqueCharm("The Gloom Ward", 0x279654u),
        new UniqueCharm("The Open Eye of Gorgorra", 0x27906au),
        new UniqueCharm("The Umbracrux", 0x278408u),
        new UniqueCharm("Thousand-Eye Reaver", 0x276dafu),
        new UniqueCharm("Tibault's Will", 0x276dd7u),
        new UniqueCharm("Tuskhelm of Joritz the Mighty", 0x279054u),
        new UniqueCharm("Wendigo Brand", 0x276ddeu),
        new UniqueCharm("Widow's Web", 0x278c9cu),
        new UniqueCharm("Will of Rathma", 0x27965au),
        new UniqueCharm("Wound Drinker", 0x278c91u),
        new UniqueCharm("Writhing Band of Trickery", 0x278406u),
        new UniqueCharm("Wushe Nak Pa", 0x278c75u),
        new UniqueCharm("Wyrdskin", 0x276dcdu),
        new UniqueCharm("X'Fal's Corroded Signet", 0x276ddbu),
        new UniqueCharm("Yen's Blessing", 0x276dc0u),
    };

    public static readonly IReadOnlyDictionary<uint, UniqueCharm> ById =
        All.ToDictionary(c => c.Id);

    public static readonly IReadOnlyDictionary<string, UniqueCharm> ByName =
        All.ToDictionary(c => c.Name, (IEqualityComparer<string>)StringComparer.OrdinalIgnoreCase);

    public static bool TryGetByName(string name, out UniqueCharm charm) =>
        ByName.TryGetValue(name.Trim(), out charm!);
}

