using System.Collections.Generic;
using System.Linq;

namespace D4BuildFilter.Core;

/// <summary>One regular unique ITEM (gear/weapon/accessory, not a charm): display name + filter id.</summary>
public sealed record UniqueItem(string Name, uint Id);

/// <summary>Every regular unique in the game (excludes unique charms — those live in
/// <see cref="UniqueCharmDatabase"/>), for the app's "Uniques" hide-list (all shown by default;
/// uncheck to hide). GENERATED from the d4data dump (maxroll data.min.json v3.1.x), 2026-07-05.</summary>
public static class UniqueItemDatabase
{
    public static readonly IReadOnlyList<UniqueItem> All = new[]
    {
        new UniqueItem("100,000 Steps", 0x1278e2u),
        new UniqueItem("Accord of the Wilds", 0x2742f2u),
        new UniqueItem("Ae'grom's Schism", 0x26e5d3u),
        new UniqueItem("Airidah's Inexorable Will", 0x1a0a9bu),
        new UniqueItem("Amulet", 0x286053u),
        new UniqueItem("Amulet of Dark Omens", 0x26f0f8u),
        new UniqueItem("Anathema of the Primes", 0x26e38eu),
        new UniqueItem("Ancients' Oath", 0x057189u),
        new UniqueItem("Antipathy Crux", 0x14d564u),
        new UniqueItem("Arcadia", 0x25d6f8u),
        new UniqueItem("Argent Veil", 0x25127bu),
        new UniqueItem("Arreat's Bearing", 0x1d04acu),
        new UniqueItem("Asheara's Khanjar", 0x072a90u),
        new UniqueItem("Assassin's Stride", 0x1fc18au),
        new UniqueItem("Autumnal Crown", 0x270f70u),
        new UniqueItem("Axial Conduit", 0x1d846du),
        new UniqueItem("Azurewrath", 0x057bb8u),
        new UniqueItem("Balazan's Maxtlatl", 0x223703u),
        new UniqueItem("Band of First Breath", 0x1e014eu),
        new UniqueItem("Bands of Ichorous Rose", 0x224737u),
        new UniqueItem("Bane of Ahjad-Den", 0x1fc162u),
        new UniqueItem("Banished Lord's Talisman", 0x17d2dcu),
        new UniqueItem("Bastion of Sir Matthias", 0x25122au),
        new UniqueItem("Battle Trance", 0x13e795u),
        new UniqueItem("Beastfall Boots", 0x1a0351u),
        new UniqueItem("Bindings of Attrition", 0x26e5e6u),
        new UniqueItem("Bitter Flamberge", 0x273e98u),
        new UniqueItem("Black River", 0x13ee7cu),
        new UniqueItem("Blood Artisan's Cuirass", 0x13ee76u),
        new UniqueItem("Blood Moon Breeches", 0x129210u),
        new UniqueItem("Blood Wake", 0x27828fu),
        new UniqueItem("Blood-Mad Idol", 0x1a3b76u),
        new UniqueItem("Bloodless Scream", 0x129e70u),
        new UniqueItem("Blue Rose", 0x127d06u),
        new UniqueItem("Boost Dagger", 0x079b75u),
        new UniqueItem("Boost Helm", 0x079b1cu),
        new UniqueItem("Boost Pants", 0x079b87u),
        new UniqueItem("Boost Scythe", 0x079b7du),
        new UniqueItem("Boost Staff", 0x0fe443u),
        new UniqueItem("Boots", 0x28604du),
        new UniqueItem("Bridle of Tor'Baalos", 0x26e5e2u),
        new UniqueItem("Browbreak Maul", 0x27693bu),
        new UniqueItem("Bucrani's Grip", 0x1f3432u),
        new UniqueItem("Bucrani's Resolve", 0x1f3436u),
        new UniqueItem("Bucrani's Tread", 0x1f342eu),
        new UniqueItem("Bucrani's Will", 0x1f3430u),
        new UniqueItem("Cage of Madness", 0x26e5deu),
        new UniqueItem("Cassia's Grace", 0x2760bcu),
        new UniqueItem("Cathedral's Song", 0x25bfc9u),
        new UniqueItem("Chainscourged Mail", 0x25d35du),
        new UniqueItem("Chest Armor", 0x28604fu),
        new UniqueItem("Cluckeye", 0x26e4bbu),
        new UniqueItem("Cluckonomicon", 0x26e4b6u),
        new UniqueItem("Condemnation", 0x06e213u),
        new UniqueItem("Coop de Grâce", 0x274088u),
        new UniqueItem("Cowl of Malefic Torment", 0x26e5dcu),
        new UniqueItem("Cowl of the Nameless", 0x078d8du),
        new UniqueItem("Craze of the Dead God", 0x1e092eu),
        new UniqueItem("Cruor's Embrace", 0x1d064bu),
        new UniqueItem("Dark Howl", 0x273986u),
        new UniqueItem("Dark Stalker's Medallion", 0x276531u),
        new UniqueItem("Dawnfire", 0x25c1dau),
        new UniqueItem("Death's Pavane", 0x129a94u),
        new UniqueItem("Deathgrip", 0x277cf2u),
        new UniqueItem("Deathless Visage", 0x12d6efu),
        new UniqueItem("Deathmask of Nirmitruq", 0x06f2edu),
        new UniqueItem("Deathspeaker's Pendant", 0x12c695u),
        new UniqueItem("Demon-Eye Sword", 0x2726f7u),
        new UniqueItem("Desperate March", 0x2764dbu),
        new UniqueItem("Dirge of Airidah", 0x273e5du),
        new UniqueItem("Dirge of Odium", 0x26e392u),
        new UniqueItem("Dolmen Stone", 0x1892c9u),
        new UniqueItem("Drognan's Anguish", 0x277736u),
        new UniqueItem("Eaglehorn", 0x08c816u),
        new UniqueItem("Earthbreaker", 0x1cb4c4u),
        new UniqueItem("Ebonpiercer", 0x1d0785u),
        new UniqueItem("Echo of Kwatli", 0x272ed0u),
        new UniqueItem("Eggcecutioner", 0x273c44u),
        new UniqueItem("Eggis", 0x274308u),
        new UniqueItem("Elegy", 0x26e38cu),
        new UniqueItem("Elias mummified finger", 0x153a46u),
        new UniqueItem("Emberfury", 0x277719u),
        new UniqueItem("Emblem of Staalbreak", 0x276526u),
        new UniqueItem("Esadora's Overflowing Cameo", 0x12b254u),
        new UniqueItem("Esu's Heirloom", 0x13eebeu),
        new UniqueItem("Etna's Lost Dagger", 0x276181u),
        new UniqueItem("Eye of Baal", 0x26e5f0u),
        new UniqueItem("Eyes in the Dark", 0x072e0bu),
        new UniqueItem("Fang of the Vipermagi", 0x2770dfu),
        new UniqueItem("Fields of Crimson", 0x047319u),
        new UniqueItem("Fist of the Iron Rose", 0x2760ebu),
        new UniqueItem("Fists of Fate", 0x02d7abu),
        new UniqueItem("Fists of War", 0x205bceu),
        new UniqueItem("Flamescar", 0x128948u),
        new UniqueItem("Flameweaver", 0x1ced1fu),
        new UniqueItem("Fleshrender", 0x061184u),
        new UniqueItem("Fleshwrit Carapace", 0x26e5acu),
        new UniqueItem("Flickerstep", 0x047355u),
        new UniqueItem("Footfalls of the Waning World", 0x26e5b2u),
        new UniqueItem("Fractured Runestone", 0x274230u),
        new UniqueItem("Fractured Winterglass", 0x1c6c65u),
        new UniqueItem("Frostburn", 0x03e301u),
        new UniqueItem("Fury of the Wilds", 0x27484eu),
        new UniqueItem("Galvanic Azurite", 0x2410edu),
        new UniqueItem("Gate of the Red Dawn", 0x24f0ccu),
        new UniqueItem("Gathlen's Birthright", 0x1fc169u),
        new UniqueItem("Gauntlets of Sheol", 0x26e5aeu),
        new UniqueItem("Gift of Frost", 0x277dc7u),
        new UniqueItem("Gladiator's Triumph", 0x215756u),
        new UniqueItem("Gloves", 0x286051u),
        new UniqueItem("Gloves of the Illuminator", 0x031a2du),
        new UniqueItem("Godslayer Crown", 0x17bafbu),
        new UniqueItem("Gohr's Devastating Grips", 0x0496bfu),
        new UniqueItem("Gospel of the Devotee", 0x2410afu),
        new UniqueItem("Grasp of Shadow", 0x13ee8bu),
        new UniqueItem("Gravewalker's Hand", 0x279d1fu),
        new UniqueItem("Greatstaff of the Crone", 0x05698cu),
        new UniqueItem("Greaves of the Empty Tomb", 0x129ea2u),
        new UniqueItem("Greenwalker's Oath", 0x273ab7u),
        new UniqueItem("Greenwalker's Signet", 0x273ec7u),
        new UniqueItem("Griswold's Opus", 0x25cbb1u),
        new UniqueItem("Guise of War", 0x205bd0u),
        new UniqueItem("Hail of Verglas", 0x1fc177u),
        new UniqueItem("Halo", 0x08d02fu),
        new UniqueItem("Hand of Apotheosis", 0x26e5d5u),
        new UniqueItem("Hands of the Worldbreaker", 0x26e5dau),
        new UniqueItem("Hangman's Hand", 0x277c1cu),
        new UniqueItem("Harmony of Ebewaka", 0x1e53dau),
        new UniqueItem("Harriers of War", 0x205bcau),
        new UniqueItem("Heart of Azgar", 0x273c57u),
        new UniqueItem("Heart of War", 0x205bccu),
        new UniqueItem("Hecaton Chasm", 0x26e597u),
        new UniqueItem("Hellbrand Signet", 0x26e5a1u),
        new UniqueItem("Hellhammer", 0x05415du),
        new UniqueItem("Hellhound's Sabatons", 0x26e5d0u),
        new UniqueItem("Helm", 0x286055u),
        new UniqueItem("Herald of Zakarum", 0x25bb4bu),
        new UniqueItem("Herald's Morningstar", 0x24f031u),
        new UniqueItem("Hesha e Kesungi", 0x2410d6u),
        new UniqueItem("Hooves of the Mountain God", 0x1f6e1du),
        new UniqueItem("Howl from Below", 0x12ba0eu),
        new UniqueItem("Hunter's Bow", 0x08c817u),
        new UniqueItem("Hunter's Zenith", 0x0f19eeu),
        new UniqueItem("Iceheart Brais", 0x13eea2u),
        new UniqueItem("Ifeh's Dire Totem", 0x273c36u),
        new UniqueItem("Indira's Memory", 0x206636u),
        new UniqueItem("Infernal Homunculus", 0x26e39eu),
        new UniqueItem("Insatiable Fury", 0x0d54b3u),
        new UniqueItem("Jacinth Shell", 0x1e0e7bu),
        new UniqueItem("Judgment of Auriel", 0x264faau),
        new UniqueItem("Judicant's Glaivehelm", 0x2554d9u),
        new UniqueItem("Kabraxis' Will", 0x26e5b0u),
        new UniqueItem("Kessime's Legacy", 0x1fc181u),
        new UniqueItem("Khamsin Steppewalkers", 0x259fe1u),
        new UniqueItem("Kilt of Blackwing", 0x2410e1u),
        new UniqueItem("Kleos, Spear of Athulua", 0x26c94eu),
        new UniqueItem("Levin Grasp", 0x277a9du),
        new UniqueItem("Lidless Wall", 0x15f736u),
        new UniqueItem("Light's Rebuke", 0x25b0d6u),
        new UniqueItem("Lightburst Hammer", 0x2311b7u),
        new UniqueItem("Litany of Sable", 0x26e39bu),
        new UniqueItem("Loyalty's Mantle", 0x1e5eeeu),
        new UniqueItem("Lurid Pact", 0x26e047u),
        new UniqueItem("Mace of King Leoric", 0x25aff6u),
        new UniqueItem("Mad Wolf's Glee", 0x0575b4u),
        new UniqueItem("Malefic Crescent", 0x1fc16fu),
        new UniqueItem("Mantle of Mountain's Fury", 0x1fc16bu),
        new UniqueItem("Mantle of the Grey", 0x25d428u),
        new UniqueItem("March of the Stalwart Soul", 0x2539a2u),
        new UniqueItem("Mark of the Old Wolf", 0x274332u),
        new UniqueItem("Might of Qual-Kehk", 0x276c3du),
        new UniqueItem("Might of the Ursine", 0x27485au),
        new UniqueItem("Misericorde", 0x2761a2u),
        new UniqueItem("Mjölnic Ryng", 0x1ec38bu),
        new UniqueItem("Moloch's Beating Flame", 0x26e5eau),
        new UniqueItem("Molten Band", 0x277679u),
        new UniqueItem("Morlu Fleshward", 0x26e5e8u),
        new UniqueItem("Mother's Embrace", 0x128a9eu),
        new UniqueItem("Mutilator Plate", 0x12afabu),
        new UniqueItem("Nails of the Gore-Crowned", 0x26e5aau),
        new UniqueItem("Night Terror", 0x26e5ecu),
        new UniqueItem("Nomad's Longing Heart", 0x276534u),
        new UniqueItem("Okun's Catalyst", 0x2092dcu),
        new UniqueItem("Omen of Pain", 0x278d92u),
        new UniqueItem("Onyx Soul", 0x277592u),
        new UniqueItem("Ophidian Iris", 0x223700u),
        new UniqueItem("Orphan Maker", 0x126753u),
        new UniqueItem("Orsivane", 0x259790u),
        new UniqueItem("Overkill", 0x12a626u),
        new UniqueItem("Pact Amulet", 0x163b0eu),
        new UniqueItem("Pact of Bone", 0x277d58u),
        new UniqueItem("Paingorger's Gauntlets", 0x17cb1du),
        new UniqueItem("Pants", 0x286057u),
        new UniqueItem("Path of the Emissary", 0x25914eu),
        new UniqueItem("Path of Trag'Oul", 0x1d8469u),
        new UniqueItem("Peacemonger's Signet", 0x1e0179u),
        new UniqueItem("Penitent Greaves", 0x032d88u),
        new UniqueItem("Pitfighter's Gull", 0x1ad4fbu),
        new UniqueItem("Protean Heart", 0x272ed2u),
        new UniqueItem("Protection of the Prime", 0x1ed343u),
        new UniqueItem("Purified Lightbringer", 0x274862u),
        new UniqueItem("PvP Refresher", 0x17eee3u),
        new UniqueItem("QA 2H Mace", 0x1da374u),
        new UniqueItem("QA 2H Scythe", 0x1da37bu),
        new UniqueItem("QA Barrier Ring", 0x0799f5u),
        new UniqueItem("QA Bow", 0x1da36fu),
        new UniqueItem("QA Chest", 0x1da3bcu),
        new UniqueItem("QA DoT Ring", 0x0a57c0u),
        new UniqueItem("QA Glaive", 0x1e5805u),
        new UniqueItem("QA HP Test Ring", 0x086c09u),
        new UniqueItem("QA Pants", 0x201a23u),
        new UniqueItem("QA Polearm", 0x1de2b3u),
        new UniqueItem("QA Staff", 0x0b121bu),
        new UniqueItem("QA Stun Hat", 0x0433dcu),
        new UniqueItem("QA Test Amulet", 0x093549u),
        new UniqueItem("QA Test Amulet - Max Cooldown", 0x202997u),
        new UniqueItem("Rage of Harrogath", 0x13e73au),
        new UniqueItem("Raiment of the Infinite", 0x0660e1u),
        new UniqueItem("Raiment of the Sea", 0x277ccfu),
        new UniqueItem("Ramaladni's Magnum Opus", 0x13e788u),
        new UniqueItem("Razorplate", 0x128a59u),
        new UniqueItem("Red Blessing", 0x2782a7u),
        new UniqueItem("Red Sermon", 0x25527eu),
        new UniqueItem("Rictus of Terror", 0x26e5e0u),
        new UniqueItem("Rimeblood", 0x277a7du),
        new UniqueItem("Ring", 0x28604bu),
        new UniqueItem("Ring of Mendeln", 0x12a7e3u),
        new UniqueItem("Ring of Misfortune", 0x1463edu),
        new UniqueItem("Ring of Red Furor", 0x1a0a6au),
        new UniqueItem("Ring of the Jinx", 0x1fdb07u),
        new UniqueItem("Ring of the Midday Hunt", 0x1e017bu),
        new UniqueItem("Ring of the Midnight Sun", 0x1e017du),
        new UniqueItem("Ring of the Ravenous", 0x1a223eu),
        new UniqueItem("Ring of the Sacrilegious Soul", 0x1a0aa4u),
        new UniqueItem("Ring of Writhing Moon", 0x1e014bu),
        new UniqueItem("Rod of Kepeleke", 0x1ff06eu),
        new UniqueItem("Rotting Lightbringer", 0x2236eeu),
        new UniqueItem("Rustbitten Dirk", 0x24fe35u),
        new UniqueItem("Saboteur's Signet", 0x1d0a18u),
        new UniqueItem("Sabre of Tsasgal", 0x2410b4u),
        new UniqueItem("Sanctis of Kethamar", 0x25c7c1u),
        new UniqueItem("Sanguivor, Blade of Zir", 0x1fc187u),
        new UniqueItem("Sashes of the Wretched", 0x26e5e4u),
        new UniqueItem("Scepter of the Three", 0x26e399u),
        new UniqueItem("Scorn of the Earth", 0x1e08beu),
        new UniqueItem("Scoundrel's Kiss", 0x1d06e9u),
        new UniqueItem("Scoundrel's Leathers", 0x189a04u),
        new UniqueItem("Scourge of Duriel", 0x26e3a0u),
        new UniqueItem("Sea Lord's Fine Gloves", 0x27616eu),
        new UniqueItem("Seal of the Ophanim", 0x26e59bu),
        new UniqueItem("Seal of the Second Trumpet", 0x25d677u),
        new UniqueItem("Seed of Horazon", 0x26e5a7u),
        new UniqueItem("Seer of the Old", 0x175ca8u),
        new UniqueItem("Sepazontec", 0x1e52f0u),
        new UniqueItem("Shanar's Resonance", 0x277124u),
        new UniqueItem("Shroud of Khanduras", 0x1d8465u),
        new UniqueItem("Shrouded Gift", 0x27665bu),
        new UniqueItem("Sidhe Bindings", 0x1f4737u),
        new UniqueItem("Signet of Pelghain", 0x2776f6u),
        new UniqueItem("Sire of Sin", 0x26e590u),
        new UniqueItem("Skyhunter", 0x057d3fu),
        new UniqueItem("Sliver of Hate", 0x2806e1u),
        new UniqueItem("Snake Glaive", 0x1bca0du),
        new UniqueItem("Soulbrand", 0x17d127u),
        new UniqueItem("Spine of Tathamet", 0x26e397u),
        new UniqueItem("Staff of Endless Rage", 0x103904u),
        new UniqueItem("Staff of Lam Esen", 0x13eec7u),
        new UniqueItem("Staff of Zerae", 0x277549u),
        new UniqueItem("Starfall Coronet", 0x1a2442u),
        new UniqueItem("Stone of Vehemen", 0x1f2ea3u),
        new UniqueItem("Storm's Companion", 0x0d6fceu),
        new UniqueItem("Strides of War", 0x205bd2u),
        new UniqueItem("Strike of Stormhorn", 0x1fc175u),
        new UniqueItem("Sunbird's Gorget", 0x1fc1a9u),
        new UniqueItem("Sunbrand", 0x265a83u),
        new UniqueItem("Sundered Night", 0x25d064u),
        new UniqueItem("Sunstained War-Crozier", 0x1ee2b3u),
        new UniqueItem("Superior Lair Key", 0x288e7eu),
        new UniqueItem("Supplication", 0x253a6au),
        new UniqueItem("Sword", 0x286049u),
        new UniqueItem("Tal Rasha's Iridescent Loop", 0x12b360u),
        new UniqueItem("Tassets of the Dawning Sky", 0x1689d8u),
        new UniqueItem("Temerity", 0x13eed6u),
        new UniqueItem("Tempest Roar", 0x13e7aau),
        new UniqueItem("The Blade of Sight Aflame", 0x270f45u),
        new UniqueItem("The Butcher's Cleaver", 0x036837u),
        new UniqueItem("The Eightfold Idol", 0x26e5a3u),
        new UniqueItem("The Fecund Seal", 0x26e59du),
        new UniqueItem("The Gloom Ward", 0x2782c1u),
        new UniqueItem("The Hand of Naz", 0x2236fdu),
        new UniqueItem("The Hemat Stone", 0x26e5eeu),
        new UniqueItem("The Maestro", 0x2767f3u),
        new UniqueItem("The Oculus", 0x15f72au),
        new UniqueItem("The Open Eye of Gorgorra", 0x276536u),
        new UniqueItem("The Relentless Heart", 0x276c39u),
        new UniqueItem("The Stillblade", 0x1c0d2eu),
        new UniqueItem("The Undercrown", 0x277d3du),
        new UniqueItem("The Unmaker", 0x1f5442u),
        new UniqueItem("Thousand-Eye Reaver", 0x26bd93u),
        new UniqueItem("Thrice-Woven Nightmare", 0x26e5d8u),
        new UniqueItem("Thundergod's Blessing", 0x277143u),
        new UniqueItem("Tibault's Will", 0x17cb7bu),
        new UniqueItem("Tuskhelm of Joritz the Mighty", 0x16ba9eu),
        new UniqueItem("Twin Strikes", 0x1d04b2u),
        new UniqueItem("Two-Handed Sword", 0x286047u),
        new UniqueItem("Ugly Bastard Helm", 0x1b4be5u),
        new UniqueItem("Unbroken Chain", 0x1d8448u),
        new UniqueItem("Unsung Ascetic's Wraps", 0x15e163u),
        new UniqueItem("Vasily's Prayer", 0x13ee66u),
        new UniqueItem("Vengeful Sinew", 0x27805du),
        new UniqueItem("VFX Testing Hat", 0x0b44d7u),
        new UniqueItem("Vision of the Firestorm", 0x27714fu),
        new UniqueItem("Ward of the White Dove", 0x2516deu),
        new UniqueItem("Waxing Gibbous", 0x13ee6bu),
        new UniqueItem("Wendigo Brand", 0x26bc52u),
        new UniqueItem("Widow's Web", 0x272efbu),
        new UniqueItem("Wildheart Hunger", 0x1d063bu),
        new UniqueItem("Will of Rathma", 0x2782cbu),
        new UniqueItem("Will of Stone", 0x270f30u),
        new UniqueItem("Wilted Potential", 0x1f6e20u),
        new UniqueItem("Windforce", 0x036b4au),
        new UniqueItem("Word of Hakan", 0x13ee93u),
        new UniqueItem("Wound Drinker", 0x1e0147u),
        new UniqueItem("Wreath of Auric Laurel", 0x2654b3u),
        new UniqueItem("Writhing Band of Trickery", 0x1a0aa2u),
        new UniqueItem("Wushe Nak Pa", 0x1eb551u),
        new UniqueItem("Wyrdskin", 0x26bd89u),
        new UniqueItem("X'Fal's Corroded Signet", 0x17cd71u),
        new UniqueItem("Yen's Blessing", 0x1c5cb4u),
    };

    public static readonly IReadOnlyDictionary<uint, UniqueItem> ById = All.ToDictionary(u => u.Id);
}

