@echo off
REM Ralph Loop test gate - auto-generated by Claude Mode Switcher
REM Project: MedicK's Might
REM Test command: dotnet test D4BuildFilter.Tests --nologo --no-build
setlocal
cd /d "C:\Sync\Projects\D4BuildFilter"
set LOG=%TEMP%\ralph-medick-s-might.log
dotnet test D4BuildFilter.Tests --nologo --no-build > "%LOG%" 2>&1
if errorlevel 1 (
    echo {"decision":"block","reason":"Tests failed for MedicK's Might. See %LOG%"}
    exit /b 0
)
exit /b 0
